#ifndef _PINMAP_H_
#define _PINMAP_H_

#define EPD_MOSI_PIN CONFIG_MOSI_PIN
#define EPD_CLK_PIN CONFIG_CLK_PIN
#define EPD_CS_PIN CONFIG_CS_PIN
#define EPD_DC_PIN CONFIG_DC_PIN
#define EPD_RST_PIN CONFIG_RST_PIN
#define EPD_BUSY_PIN CONFIG_BUSY_PIN

#define DRIVER_SLEEP 2
#define DRIVER_IN_1 18
#define DRIVER_IN_2 19

#define FLOW_IN 21

#endif